apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunilapp
  labels:
    app: sunil  
  namespace: default    
spec:
  selector:
    matchLabels:
      app: sunilapp
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 35%
      maxUnavailable: 35%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sunilapp
    spec:
      containers:
      - name: sunilapp
        image: mrsunilmehta/project5
          imagePullPolicy: Always        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
        ports:
        - containerPort: 8080
