apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunilapp
  labels:
    app: sunilapp  
  namespace: default    
spec:
  selector:
    matchLabels:
      app: sunilapp
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sunilapp
    spec:
      containers:
        - image: mrsunilmehta/project5
          imagePullPolicy: Always        
          name: sunilapp          
          ports:
            - containerPort: 8080
